### ISSUE TITLE
Documentation: Scenario Segregation based on OWASP Top 10

### ISSUE THREAD

**Issue by 0xCardinal** [madhuakula/kubernetes-goat#104]
Pasting in the the details here from the Discord Thread - 
- K01: Insecure Workload Configurations
    - DIND
    - DoS
- K02: Supply Chain Vulnerabilities
    - Docker Registry
- K03: Overly Permissive RBAC Configurations
    - RBAC Least Privileged
- K04: Lack of Centralized Policy Enforcement
    - Kyverno
- K05: Inadequate Logging and Monitoring
    - Sysdig Faclo
    - Cilium Tetragon
- K06: Broken Authentication Mechanisms
    - Unauthenticated Cluster
    - RBAC Least Privileged
- K07: Missing Network Segmentation Controls
    - Namespace Bypass
    - NSP
- K08: Secrets Management Failures
    - Secrets in Codebase
    - Kubernetes Secrets
- K09: Misconfigured Cluster Components
    - Cluster Misconfigs
- K10: Outdated and Vulnerable Kubernetes Components
    - Helm Tiller
    - Older Versions

Task - 
- [ ] Making the documentation enhancement to add the above mentioned list with additional details

**Comment by madhuakula** [comment]
Hey, Thank you so much @0xCardinal for the issue. 

Basically, you need to create a section in the docs saying OWASP Top10 Kubernetes and create a table mapping all those stuff. Also, create some fancy way to showcase with image or mapping as well for a nicer way

Also, each scenario points back-references to the OWASP top 10 links

**Comment by madhuakula** [comment]
Thanks a lot, @0xCardinal once again. Moving this to done with #107 🚀
