### ISSUE TITLE
Error: Could not find kubectl or an other error happend, please check kubectl setup.

### ISSUE THREAD

**Issue by Goli-git** [madhuakula/kubernetes-goat#105]
After the kubectl installation, when want to run: "bash setup-kubernetes-goat.sh", an error will be shown:
Error: Could not find kubectl or another error happend, please check kubectl setup.

I assume it because of the warning error which kubernetes mentined also in their documentation.  (https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/).

Is there any solution?

**Comment by madhuakula** [comment]
Hey @Goli-git 

Thanks for trying it out. Yes, looks like you need to have first installed `kubectl` tool in your system to setup the Kubernets Goat. Also, you need to have the Kubernetes Cluster with admin rights.

- Based on your operating system you can use this to install `kubectl` https://kubernetes.io/docs/tasks/tools/#kubectl
- Also you can set up the cluster either using CSP(Cloud Service Provider) or local ones using Vagrant, Minikube, KIND, etc.

Feel free to join our discord community and there are a lot of folks to help you!
https://madhuakula.com/kubernetes-goat/docs/kubernetes-goat-community

**Comment by Goli-git** [comment]
Hey @madhuakula, thanks for the fast reply.  I have already followed the instruction but that error still is occurring.
