### ISSUE TITLE
Typo in docker image `madhuakula/k8s-goat-helm-tiller`

### ISSUE THREAD

**Issue by timip** [madhuakula/kubernetes-goat#12]
In Scenario 9 "Helm v2 tiller to PwN the cluster", there is a typo in `/pwnchart/values.yaml` inside docker image `madhuakula/k8s-goat-helm-tiller`. The namespace should be `default`.

```
root@bash:/pwnchart# cat values.yaml 
# Default values for connectivity-check.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: deafult
name: default
```

**Comment by madhuakula** [comment]
Thanks for the issue @timip. Fixed and pushed to registry :)
