### ISSUE TITLE
goat running on Microk8s - failure on internal-proxy-deployment

### ISSUE THREAD

**Issue by NetEyes** [madhuakula/kubernetes-goat#123]
i managed to run the goat in microk8s, but the internal-proxy-deployment status is "CrashLoopBackOff". 
Any reason why is that?

**Comment by NetEyes** [comment]
![Screenshot01](https://github.com/madhuakula/kubernetes-goat/assets/20463433/af4c25e4-6bef-482b-8099-3d41ad6c89f7)

**Comment by madhuakula** [comment]
Hi @NetEyes,

As you see it has 2 pods and I see 1 is ready and another one is failing. Could you please check the resources and also see if any error/messages info.

Thank you!

**Comment by NetEyes** [comment]
I resolved the issue but repeating the installation process.
