### ISSUE TITLE
ERROR: (gcloud.beta.container.clusters.create) ResponseError: code=500, message=Internal error encountered.

### ISSUE THREAD

**Issue by SaurabhSinghDev** [madhuakula/kubernetes-goat#13]
While following the setup as mentioned on [https://madhuakula.com/kubernetes-goat/kubernetes-cluster/gke.html](url) 
have encountered following error  "ERROR: (gcloud.beta.container.clusters.create) ResponseError: code=500, message=Internal error encountered."

**Comment by madhuakula** [comment]
Looks like that version is deprecated in Google cloud. Checkout "1.16.13-gke.1"
