### ISSUE TITLE
[Sensitive keys in codebases]It may be referencing an old version of TruffleHog(V2)？

### ISSUE THREAD

**Issue by rufherg** [madhuakula/kubernetes-goat#130]
## Scene
I find that trufflehog may not be find the secrets when I try to use the latest version of trufflehog.
See this issue for details
https://github.com/trufflesecurity/trufflehog/issues/1601

Do you need to optimize your pod to support the latest version?

**Comment by bubnovd** [comment]
Same issue

**Comment by madhuakula** [comment]
Done, pushed the changes with new updates

**Comment by rgov** [comment]
Just noting here that entropy-based detection of secrets seems to have been removed in TruffleHog v3. It does not detect the credential automatically because the access key ID in the challenge starts with `AKIV` and the regex that TruffleHog uses is `((?:AKIA|ABIA|ACCA)[A-Z0-9]{16})`.
