### ISSUE TITLE
Rename scenario folder to 0x

### ISSUE THREAD

**Issue by za** [madhuakula/kubernetes-goat#131]
Hi there @madhuakula 

What if we rename the scenario folder name to:

```
00-...
01-...
02-...
...
11-...
```

so it's easier to see when we sort it.

This is #minor amd #noturgent

**Comment by za** [comment]
Hi @madhuakula any opinion/response about this?

**Comment by madhuakula** [comment]
Good idea, make sense @za . Also there are some other changes coming up soon, will follow up this approach.

Thnank you!

**Comment by za** [comment]
Wow, what are they? @madhuakula 

I can initiate a PR just for the renaming if we want to.
