### ISSUE TITLE
port '1234' is not open

### ISSUE THREAD

**Issue by lzwgiter** [madhuakula/kubernetes-goat#140]
- CentOS 7
- K8s version: 1.22.2

Hi, I'm trying to install k8s goat into my cluster. After running scripts `setup-kubernetes-goat.sh` and `access-kubernetes-goat.sh`. I had checked the status of all pods. However, none of nodes in my cluster have opened `1234` port. Below are the pods, deployments status:
![1](https://github.com/madhuakula/kubernetes-goat/assets/33475803/b1533348-d67c-4c82-a64f-1d61726a46ad)

**Comment by lzwgiter** [comment]
I check the command in the `access-kubernetes-goat.sh`, below is the output of `port-forward` command:
![2](https://github.com/madhuakula/kubernetes-goat/assets/33475803/fe861bbb-cc40-405d-838d-bce4825a95c6)

then I check the .kube/config file, in the context, it shows the user is `kubernetes-admin@kubernetes
`:
![3](https://github.com/madhuakula/kubernetes-goat/assets/33475803/b716d13d-a456-40e6-b47a-3e0dab999091)

How to solve this problem(crying

**Comment by madhuakula** [comment]
Could you please check your local firewall or also run `netstat -antlp` and check the ports and interfaces?
