### ISSUE TITLE
kubectl validation fails

### ISSUE THREAD

**Issue by dg0002** [madhuakula/kubernetes-goat#144]
kubectl validation fails: 

```
└─$ bash setup-kubernetes-goat.sh      
Error: Could not find kubectl or an other error happened, please check kubectl setup.
```

I deleted the kubectl check in setup-kubernetes-goat.sh for it to work

kali-linux 2023.3

**Comment by ExpelioKeev** [comment]
Also had this^ issue and it worked for me

**Comment by madhuakula** [comment]
It got fixed, Apologies for the delay. Thank you @pichuang
