### ISSUE TITLE
Could not install using KIND

### ISSUE THREAD

**Issue by minhnq1618** [madhuakula/kubernetes-goat#148]
i could not use kind to create the cluster for this because if i ran kind, it will mess up my VM Machine DNS, which make creating Container impossible, how can i fix this ? sorry i dont know what information to give you for this matter. If you need more information please let me know.

![image](https://github.com/madhuakula/kubernetes-goat/assets/81002476/1bbc9d39-4e14-4c6e-862d-b50bd3dc6917)

**Comment by gvoden** [comment]
I am able to successfully run K8S Goat in a KIND cluster running on my Windows 10 laptop. ImagePullBackOff usually means your cluster cannot fetch the image over the Internet. Could be DNS, firewall or some other network issue.

**Comment by minhnq1618** [comment]
Yes, i added a new NIC and the installation was complete, i guess during the installation, my original NIC was cut off from going to the internet for some reason :/
