### ISSUE TITLE
madhuakula/k8s-goat-system-monitor only available for amd64 architecture

### ISSUE THREAD

**Issue by piergiorgioladisa** [madhuakula/kubernetes-goat#153]
As mentioned in the title, I noticed that the ```madhuakula/k8s-goat-system-monitor``` image is available for ```amd64``` architectures. Would it be possible to have a version available for ```arm64``` as well?

**Comment by madhuakula** [comment]
It should be available for both, let me double-check again from my end.

**Comment by za** [comment]
Hi @piergiorgioladisa are you looking for this?

https://github.com/madhuakula/kubernetes-goat/blob/master/infrastructure/system-monitor/Dockerfile#L8

**Comment by madhuakula** [comment]
It's available now. Closing this ticket.

Reference: https://hub.docker.com/repository/docker/madhuakula/k8s-goat-system-monitor/tags

Thank you

**Comment by rgov** [comment]
The container image is available for arm64 now but it cannot execute on an Apple Silicon Mac:

```
{"msg":"exec container process `/usr/local/bin/gotty`: Exec format error","level":"error","time":"2025-05-11T19:17:33.974792Z"}
```

The binary is 32-bit ARM:

```
# file gotty
gotty: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, Go BuildID=b35f208e4f7e43a55999be082739d6efa7fe63d8, with debug_info, not stripped
```
