### ISSUE TITLE
Kubernetes GOAT exposure 

### ISSUE THREAD

**Issue by davidaavilar** [madhuakula/kubernetes-goat#156]
Hello, how can we expose this app to the internet? I see we can execute "access-kubernetes.sh" to expose the app internally. How can we do it using LoadBalancer SVC type on CSPs (AWS for example)? Thanks!

**Comment by za** [comment]
Hi @davidaavilar IMHO, it's not recommended to expose this app to the Internet as it's vulnerable. It might make your cloud account gets breached.

**Comment by madhuakula** [comment]
Yes, it's recommended to not be exposed to the internet. If you really wanted to expose, yes you can leverage the service type `LoadBalancer`. You can also use ingress as well to expose.
