### ISSUE TITLE
system-monitor-deployment pod in CrashLoopBackOff with no apparent fix

### ISSUE THREAD

**Issue by rholl15** [madhuakula/kubernetes-goat#160]
After running setup-kubernetes-goat.sh, the pod ReplicaSet/system-monitor-deployment-5d49dd76b9 throws this cryptic error: 
Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting cgroup config for procHooks process: unable to freeze: unknown

Events:
  Type     Reason     Age                     From               Message
  ----     ------     ----                    ----               -------
  Normal   Scheduled  8m                      default-scheduler  Successfully assigned default/system-monitor-deployment-5d49dd76b9-mbjc4 to ip-192-168-20-3.ec2.internal
  Normal   Pulled     7m56s                   kubelet            Successfully pulled image "madhuakula/k8s-goat-system-monitor" in 2.745s (2.745s including waiting). Image size: 71302365 bytes.
  Normal   Pulled     7m55s                   kubelet            Successfully pulled image "madhuakula/k8s-goat-system-monitor" in 93ms (93ms including waiting). Image size: 71302365 bytes.
  Normal   Started    7m38s (x3 over 7m56s)   kubelet            Started container system-monitor
  Normal   Pulled     7m38s                   kubelet            Successfully pulled image "madhuakula/k8s-goat-system-monitor" in 97ms (97ms including waiting). Image size: 71302365 bytes.
  Normal   Created    7m6s (x4 over 7m56s)    kubelet            Created container system-monitor
  Normal   Pulled     7m6s                    kubelet            Successfully pulled image "madhuakula/k8s-goat-system-monitor" in 110ms (110ms including waiting). Image size: 71302365 bytes.
  Warning  Failed     7m6s                    kubelet            Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting cgroup config for procHooks process: unable to freeze: unknown
  Normal   Pulling    6m22s (x5 over 7m59s)   kubelet            Pulling image "madhuakula/k8s-goat-system-monitor"
  Normal   Pulled     6m22s                   kubelet            Successfully pulled image "madhuakula/k8s-goat-system-monitor" in 105ms (105ms including waiting). Image size: 71302365 bytes.
  Warning  BackOff    2m50s (x24 over 7m54s)  kubelet            Back-off restarting failed container system-monitor in pod system-monitor-deployment-5d49dd76b9-mbjc4_default(2b4b66f3-8ca1-42a1-bc3d-d3174ca268fb)

As best I could research this appears to be a node level issue. Very cryptic error to me and my experience level.
Would reverting to an older version of k8s on EKS work here? I will be trying this asap. I followed all documentation steps as written.
Kubernetes version - 1.30
Platform version - eks.5

**Comment by za** [comment]
Hi @rholl15 

this is strange, as I have no issue while deploying on AWS EKS using k8s version 1.30

```
$ bash setup-kubernetes-goat.sh
$ bash access-kubernetes-goat.sh
```

```
➜  kubernetes-goat git:(master) ✗ k logs -f system-monitor-deployment-5d49dd76b9-5s86t 
2024/07/29 08:02:57 GoTTY is starting with command: bash
2024/07/29 08:02:57 Permitting clients to write input to the PTY.
2024/07/29 08:02:57 HTTP server is listening at: http://:::8080/
2024/07/29 08:02:57 Alternative URL: http://127.0.0.1:8080/
2024/07/29 08:02:57 Alternative URL: http://::1:8080/
2024/07/29 08:02:57 Alternative URL: http://192.168.56.94:8080/
2024/07/29 08:02:57 Alternative URL: http://fe80::386e:90ff:fe9c:635:8080/
```

```
➜  kubernetes-goat git:(master) ✗ kubectl get pods
NAME                                               READY   STATUS    RESTARTS   AGE
system-monitor-deployment-5d49dd76b9-5s86t         1/1     Running   0          99m
```

How did you create EKS cluster? Did you follow this step https://madhuakula.com/kubernetes-goat/docs/how-to-run/kubernetes-goat-on-aws-amazon-web-services ?

**Comment by rholl15** [comment]
Hi @za! Thanks for your help in advance!

Yes I followed the _setup_ steps exactly. Kinda hard to mess that part up, it's great.
But.. I did use previous installations of aws cli and eksctl that I had downloaded for past projects.
Do you think the versions of my CLI tools could affect this? This is the only way I deviated from the docs in anyway.

eksctl version - 0.187.0

Kubectl:
Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.2-eks-db838b0

aws-cli/2.11.19 Python/3.11.3 Darwin/23.5.0 exe/x86_64 prompt/off

**Comment by za** [comment]
Hi @rholl15 so, other pods are deployed successfully. I can see their running statuses. BTW, what instance type did you use while deploying EKS? And how many workers you set?

**Comment by za** [comment]
Maybe you can try upgrading your aws-cli version. This is mine @rholl15 :
```
➜  ~ aws --version
aws-cli/2.15.40 Python/3.11.8 <snipped>
```

**Comment by madhuakula** [comment]
Fixed in the new docker image. Moving this to Done.
