### ISSUE TITLE
helm2 is end of life very soon

### ISSUE THREAD

**Issue by walidshaari** [madhuakula/kubernetes-goat#18]
I believe you do not need helm2 any longer [helm2 deprecation timeline](https://helm.sh/blog/helm-v2-deprecation-timeline/)
your deployment setup looks straightforward

**Comment by madhuakula** [comment]
Hello @walidshaari 

Thanks for asking. The entire use case of having helm2 is to showcase the vulnerable scenario as part of Kubernetes security learning.

So, it's not that we can't migrate to helm3 but we wanted to use helm2 intentionally as it is part of the scenarios to teach about helm security misconfiguration

**Comment by walidshaari** [comment]
oh! makes sense. thank you for answering promptly and awesome project
