### ISSUE TITLE
Health Check Deployment Pod not running

### ISSUE THREAD

**Issue by vineetapte** [madhuakula/kubernetes-goat#23]
After I run setup-kubernetes-goat.sh script, all pods are in running state except of Health Check Deployment pod. I see error "MountVolume.SetUp failed for volume "docker-sock-volume" : hostPath type check failed: /var/run/docker.sock is not a file" in dashboard. The pod is in stuck in ContainerCreating state.

Env config:
Windows 10 Home, WSL2, Docker for Desktop, Ubuntu-18.04, Minikube (v1.16.0).

![image](https://user-images.githubusercontent.com/5180174/104558228-7d144500-5668-11eb-8698-f9363376c867.png)

![image](https://user-images.githubusercontent.com/5180174/104558374-b51b8800-5668-11eb-84eb-4965f08644f0.png)

![image](https://user-images.githubusercontent.com/5180174/104558299-9ae1aa00-5668-11eb-88e3-b1dcae4e9526.png)

**Comment by vineetapte** [comment]
Update: If I setup Kubernetes Goat using Kind, all pods are running.
![image](https://user-images.githubusercontent.com/5180174/104570388-dc2d8600-5677-11eb-8168-5fbb3136cfa9.png)

Whereas if Minikube is used, Health Check Deployment pod is stuck in ContainerCreating state.

**Comment by madhuakula** [comment]
Hello @vineetapte 

Looks like the socket is not available for the above setup and the second one, could you please see the logs by checking the `kubectl describe pod <podname>` to see why it's in the ContainerCreating state.

Cheers!

**Comment by vineetapte** [comment]
Logs for the health check deployment pod.

**kubectl describe pod health-check-deployment-57c65cf5db-tzhd6**
Name:           health-check-deployment-57c65cf5db-tzhd6
Namespace:      default
Priority:       0
Node:           minikube/192.168.49.2
Start Time:     Sun, 17 Jan 2021 13:01:20 +0530
Labels:         app=health-check
                pod-template-hash=57c65cf5db
Annotations:    <none>
Status:         Pending
IP:
IPs:            <none>
Controlled By:  ReplicaSet/health-check-deployment-57c65cf5db
Containers:
  health-check:
    Container ID:
    Image:          madhuakula/k8s-goat-health-check
    Image ID:
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     30m
      memory:  100Mi
    Requests:
      cpu:        30m
      memory:     100Mi
    Environment:  <none>
    Mounts:
      /custom/docker/docker.sock from docker-sock-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-fj9ph (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  docker-sock-volume:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/docker.sock
    HostPathType:  File
  default-token-fj9ph:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-fj9ph
    Optional:    false
QoS Class:       Guaranteed
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason       Age                 From               Message
  ----     ------       ----                ----               -------
  Normal   Scheduled    10m                 default-scheduler  Successfully assigned default/health-check-deployment-57c65cf5db-tzhd6 to minikube
  Warning  FailedMount  6m35s               kubelet            Unable to attach or mount volumes: unmounted volumes=[docker-sock-volume], unattached volumes=[docker-sock-volume default-token-fj9ph]: timed out waiting for the condition
  Warning  FailedMount  2m (x3 over 8m49s)  kubelet            Unable to attach or mount volumes: unmounted volumes=[docker-sock-volume], unattached volumes=[default-token-fj9ph docker-sock-volume]: timed out waiting for the condition
  Warning  FailedMount  36s (x13 over 10m)  kubelet            MountVolume.SetUp failed for volume "docker-sock-volume" : hostPath type check failed: /var/run/docker.sock is not a file

Let me know if you need any more information.

**Comment by macagr** [comment]
Sorry for pitching in. I saw something similar when working to make the Kind script. There are two things I think may be causing this error: 

1. Docker is not the container runtime used by the container/VM that contains the node in Minikube (maybe the `--container-runtime` option or something like that?), and therefore there is not a Docker socket to actually mount. Not sure how to fix this, I may play around on the weekend.  
2. If Docker is being used as a container runtime, then it could be the case that for some reason (not sure why), it is not correctly inferring the type of the socket file and you could try to remove the `type: File` on line 33 of the `deployment.yaml` file in  `/scenarios/health-check`.

Let me know if you agree with these possibilities, @madhuakula. Thanks!

**Comment by madhuakula** [comment]
Hi @vineetapte 

I agree with @macagr and also looking at your logs, the docker socket file is not available. This means either the host runtime might not be Docker or the `docker.sock` volume mount is missing the proper path from the host system.

Thank you!

**Comment by vineetapte** [comment]
Hi @macagr and @madhuakula  Thanks for the input. Docker is the runtime. I will check on this, why docker.sock volume is missing from path. Will get back to you.

**Comment by vineetapte** [comment]
As suggested by @macagr, I removed the type: File on line 33 of the deployment.yaml file in /scenarios/health-check and it worked.

**Comment by macagr** [comment]
@vineetapte I'm glad that you got it to run. I do think this is a very weird behavior. Can you perhaps let me know what is the version of KinD are you using? I may drop a question in the KinD community, because I had something similar happen to me, and I am not sure it is intended.

**Comment by vineetapte** [comment]
@macagr I had no issues in setting up and running Kubernetes goat in KinD. Scripts in kind-setup folder worked fine and all pods were in running state. KinD version 'kind v0.7.0 go1.13.6'
I was having issues when I tried to set-up Kubernetes goat in Minikube. The Health Check Deployment pod got stuck in ContainerCreating state. That's when I removed the `type:File` from the `deployment.yaml` file and it worked. 
Changing `type:File` to `type:Socket` in the yaml file also works. The health check pod is now running.

**Comment by madhuakula** [comment]
Thank you so much both of you. I really appreciate all you awesome people trying out Kubernetes Goat and sharing feedback and helping each other :pray:

**Comment by madhuakula** [comment]
Hey @vineetapte 

Shall I close this issue now?

Thank you

**Comment by vineetapte** [comment]
Sure @madhuakula Will you make changes to deployment.yaml file?

**Comment by macagr** [comment]
@madhuakula I think it would be good to check if the `type: Socket` is a good solution about these deployment issues. But perhaps, we need more testing? I can make a few checks in the coming week.

**Comment by jrknox1977** [comment]
I am running k8s-goat on a kubeadm cluster. I had to modify the scenarios/health-check/deployment.yaml --> 
```
      volumes:
        - name: docker-sock-volume
          hostPath:
            path: /var/run/containerd/containerd.sock
            type: Socket
```
changed it to point at containerd and it worked.

**Comment by stephenbradshaw** [comment]
For microk8s the containerd socket file is located at `/var/snap/microk8s/common/run/containerd.sock`, so you need to modify `scenarios/health-check/deployment.yaml` like so:

```
      volumes:
        - name: docker-sock-volume
          hostPath:
            path: /var/snap/microk8s/common/run/containerd.sock
            type: Socket
```

**Comment by za** [comment]
> I am running k8s-goat on a kubeadm cluster. I had to modify the scenarios/health-check/deployment.yaml -->
> 
> ```
>       volumes:
>         - name: docker-sock-volume
>           hostPath:
>             path: /var/run/containerd/containerd.sock
>             type: Socket
> ```
> 
> changed it to point at containerd and it worked.

Hi @madhuakula I'm also having this issue when applying this `deployment.yaml` file on CIS Docker:

```
$ kubectl apply -f scenarios/docker-bench-security/deployment.yaml 
```

Replacing to `path: /var/run/containerd/containerd.sock` solves the issue.
