### ISSUE TITLE
Update to teardown-cluster.sh

### ISSUE THREAD

**Issue by vineetapte** [madhuakula/kubernetes-goat#24]
Last line is script '**kind delete clusters kubernetes-goat-cluster**' should be updated to '**kind delete clusters --name kubernetes-goat-cluster**'

As per the Kind docs, to delete a cluster, **--name** (flag) needs to be used.

**Comment by madhuakula** [comment]
Hey @vineetapte 

I think that should be fine as it mentioned `clusters`.

Anyway, I have fixed and updated it.

Thanks
