### ISSUE TITLE
Which version of Kubernetes is best with GOAT?

### ISSUE THREAD

**Issue by un-fuf-a-doo** [madhuakula/kubernetes-goat#29]
In the latest version of kubernetes (v1.21) at least one pod does not start up. It stays in a Completed status and no amount of pushing fixes the issue.  So since it is not documented anywhere, I figured I would ask here.

Is there a specific version that has been tested with goat?

Thanks,
JPop

**Comment by madhuakula** [comment]
Hi @un-fuf-a-doo 

Thank you so much for checking. I agree that there is no mention of the specific version, I think it's always better to use as lower a version as possible to showcase the known vulnerabilities. Ideally, I wanted to create that cluster environment as well to showcase some cluster setup-related vulnerabilities in the future.

But for now, I think it should even work with 1.21 as the completed status should be fine, as that is a job. I think you are all set if you see the below output.

![katacoda-kubernetes-goat-pods](https://user-images.githubusercontent.com/6764192/120918186-60c68280-c6b3-11eb-8087-7f1db9e9d53c.png)

Thank you so much once again, let me update the documentation as well with some context around the version information and also about the status check for the complete deployment 🙏
