### ISSUE TITLE
[Require] Support helm3 for setting up the environment

### ISSUE THREAD

**Issue by Aju100** [madhuakula/kubernetes-goat#33]
Helm is a tool for managing Charts. Helm2 has been depreciated and need to update the version so we can easily setup the k8s goat in our cluster instead of setting up the version(2) of helm. 

![helm2](https://user-images.githubusercontent.com/29862610/122659140-5072d500-d194-11eb-910a-51765aad3d66.png)

**Comment by madhuakula** [comment]
Hi @Aju100 

That's an intentionally vulnerable scenario, where I am trying to showcase the helm tiller vulnerability misconfiguration.

So it is required as part of teaching vulnerable Kubernetes security.

Thank you!

**Comment by vishal-biyani** [comment]
Hey @madhuakula I was actually thinking of adding support for Helm3 but saw your comment. Now that Helm2 is deprecated - does it make sense for us to still use Helm2 for showing these scenarios, instead should we not use Helm3 and cover relevant scenarios?
