### ISSUE TITLE
Falco - api version error

### ISSUE THREAD

**Issue by jonnythefox** [madhuakula/kubernetes-goat#34]
Hi - I receive an error when trying to deploy the Falco tool using the helm chart. I used the script method to deploy the stable version of Helm for Ubuntu which appears to have installed Client and Server v2.17.0, and I sym linked the binary as helm2 as per the deployment instructions for GOAT. However, I receive an API version error when trying to deploy Falco using the chart, which I think may be due to Falco now supporting Helm v3? Question is, if I deploy Helm v3 will it defeat any of the labs that rely on Helm, notably "Helm V2 tiller to pwn the cluster"?

**Comment by madhuakula** [comment]
Hi @jonnythefox 

Thanks for the issue. 

Yes, you are absolutely correct. If we completely use helm3 it defeats the purpose of the scenario "Helm V2 tiller pwn the cluster". 

For practicing the Falco scenario, I think it would be great if you can remove the tiller component and deploy it with Helm V3 by adding the Falco repository. 

I will keep this issue and try to update the documentation and notes. Also soon, I will be trying to work on making some scenarios deprecated like Helm2 as they are not used by anyone. But I will keep them documented but remove/deprecate them from the scenarios 🙂 

Thanks a ton once again for trying the project, please do provide if you have any feedback, suggestion, and inputs 🙏

**Comment by jonnythefox** [comment]
Thanks Madhu - I've cloned my vm so I can run the v3 helm and deploy Falco via that route. All is good!
