### ISSUE TITLE
Helm2 install help

### ISSUE THREAD

**Issue by Gfuen** [madhuakula/kubernetes-goat#37]
I have been able to install Helm version 2.17 from the official Github binary release but when I try to run "helm2 version" I get a command not found even though a "helm version" returns 2.17. Additionally, when I try to run the setup-kubernetes-goat script I get the following error "Error" Could not find helm2, please check helm2 setup.". Any help will be appreciated on what I am doing wrong for the required helm installation. Thanks.

**Comment by madhuakula** [comment]
Thanks @Gfuen 

Glad it's working :)
