### ISSUE TITLE
Arm64 - Container issue

### ISSUE THREAD

**Issue by phpsystems** [madhuakula/kubernetes-goat#47]
Hi,

Thanks for your work on porting to Arm64! I have started to spin it up on my cluster today and I am getting:

$ kubectl logs hunger-check-deployment-cc7758676-4zzkk -n big-monolith
standard_init_linux.go:219: exec user process caused: exec format error

Deployment was via the setup script as normal. Am I missing something, like a parameter to pass to that script?

Regards,
Tim

**Comment by phpsystems** [comment]
Output from kubectl, incase it helps:

$ kubectl get all -A
NAMESPACE           NAME                                                   READY   STATUS              RESTARTS         AGE
big-monolith        pod/hunger-check-deployment-cc7758676-4zzkk            0/1     Error               0                18m
default             pod/batch-check-job-glvpx                              0/1     Completed           0                18m
default             pod/build-code-deployment-64f9dc8b78-dr98t             0/1     ContainerCreating   0                18m
default             pod/health-check-deployment-f9d6f6f9c-mccv4            0/1     ContainerCreating   0                18m
default             pod/hidden-in-layers-qddd4                             1/1     Running             0                18m
default             pod/internal-proxy-deployment-567dc6dcb5-c8bcw         0/2     ContainerCreating   0                18m
default             pod/kubernetes-goat-home-deployment-866d467dfd-g88t7   0/1     ContainerCreating   0                18m
default             pod/metadata-db-58c7b5d45b-q87qt                       0/1     ContainerCreating   0                18m
default             pod/poor-registry-deployment-5dbb7ccddb-jhplr          0/1     ContainerCreating   0                18m
default             pod/system-monitor-deployment-69477d6d49-zb4qd         0/1     ContainerCreating   0                18m
kube-system         pod/coredns-6bfdc44458-b6l76                           1/1     Running             16 (4d18h ago)   5d21h
kube-system         pod/coredns-6bfdc44458-vkq6n                           1/1     Running             17 (4d18h ago)   5d21h
secure-middleware   pod/cache-store-deployment-754d469fdc-6x2fp            1/1     Running             0                18m

NAMESPACE           NAME                                      TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)                  AGE
big-monolith        service/hunger-check-service              ClusterIP   10.32.0.203   <none>        8080/TCP                 18m
default             service/build-code-service                ClusterIP   10.32.0.191   <none>        3000/TCP                 18m
default             service/health-check-service              ClusterIP   10.32.0.144   <none>        80/TCP                   18m
default             service/internal-proxy-api-service        ClusterIP   10.32.0.114   <none>        3000/TCP                 18m
default             service/internal-proxy-info-app-service   NodePort    10.32.0.115   <none>        5000:30003/TCP           18m
default             service/kubernetes                        ClusterIP   10.32.0.1     <none>        443/TCP                  12d
default             service/kubernetes-goat-home-service      ClusterIP   10.32.0.150   <none>        80/TCP                   18m
default             service/metadata-db                       ClusterIP   10.32.0.39    <none>        80/TCP                   18m
default             service/poor-registry-service             ClusterIP   10.32.0.122   <none>        5000/TCP                 18m
default             service/system-monitor-service            ClusterIP   10.32.0.249   <none>        8080/TCP                 18m
kube-system         service/kube-dns                          ClusterIP   10.32.0.10    <none>        53/UDP,53/TCP,9153/TCP   12d
secure-middleware   service/cache-store-service               ClusterIP   10.32.0.181   <none>        6379/TCP                 18m

NAMESPACE           NAME                                              READY   UP-TO-DATE   AVAILABLE   AGE
big-monolith        deployment.apps/hunger-check-deployment           0/1     1            0           18m
default             deployment.apps/build-code-deployment             0/1     1            0           18m
default             deployment.apps/health-check-deployment           0/1     1            0           18m
default             deployment.apps/internal-proxy-deployment         0/1     1            0           18m
default             deployment.apps/kubernetes-goat-home-deployment   0/1     1            0           18m
default             deployment.apps/metadata-db                       0/1     1            0           18m
default             deployment.apps/poor-registry-deployment          0/1     1            0           18m
default             deployment.apps/system-monitor-deployment         0/1     1            0           18m
kube-system         deployment.apps/coredns                           2/2     2            2           12d
secure-middleware   deployment.apps/cache-store-deployment            1/1     1            1           18m

NAMESPACE           NAME                                                         DESIRED   CURRENT   READY   AGE
big-monolith        replicaset.apps/hunger-check-deployment-cc7758676            1         1         0       18m
default             replicaset.apps/build-code-deployment-64f9dc8b78             1         1         0       18m
default             replicaset.apps/health-check-deployment-f9d6f6f9c            1         1         0       18m
default             replicaset.apps/internal-proxy-deployment-567dc6dcb5         1         1         0       18m
default             replicaset.apps/kubernetes-goat-home-deployment-866d467dfd   1         1         0       18m
default             replicaset.apps/metadata-db-58c7b5d45b                       1         1         0       18m
default             replicaset.apps/poor-registry-deployment-5dbb7ccddb          1         1         0       18m
default             replicaset.apps/system-monitor-deployment-69477d6d49         1         1         0       18m
kube-system         replicaset.apps/coredns-6bfdc44458                           2         2         2       12d
secure-middleware   replicaset.apps/cache-store-deployment-754d469fdc            1         1         1       18m

NAMESPACE   NAME                         COMPLETIONS   DURATION   AGE
default     job.batch/batch-check-job    1/1           2m7s       18m
default     job.batch/hidden-in-layers   0/1           18m        18m

**Comment by phpsystems** [comment]
Same issue with the system monitor:

$ kubectl logs system-monitor-deployment-69477d6d49-zb4qd
standard_init_linux.go:219: exec user process caused: exec format error

**Comment by phpsystems** [comment]
$ uname -m
aarch64

For the binaries used in these containers (gotty), would something like this work?:

RUN apt update && apt install stress-ng curl wget -y \
    && cd /tmp; \
    if [ `uname -m` == "aarch64" ]; then \
        GOTTY="gottty_linux_arm.tar.gz" \
    else \
        GOTTY="gotty_linux_amd64.tar.gz" \
    fi; \
    wget https://github.com/yudai/gotty/releases/download/v1.0.1/$GOTTY \
    && tar -xvzf $GOTTY; mv gotty /usr/local/bin/gotty

**Comment by phpsystems** [comment]
I have tested the arm version on the arm64 architecture - it appears to run fine.

**Comment by phpsystems** [comment]
Appears to be a partial duplicate with #46 - Certainly one of the containers is mentioned in both.

**Comment by phpsystems** [comment]
Potential (ie untested) new Dockerfile attached for the hunger-check. Certainly, this command seems to give the right output on arm64:

 $ if [ `uname -m` == "aarch64" ]; then GOTTY="gottty_linux_arm.tar.gz"; else GOTTY="gotty_linux_amd64.tar.gz";     fi;
 $ echo $GOTTY
gottty_linux_arm.tar.gz


[Dockerfile.txt](https://github.com/madhuakula/kubernetes-goat/files/8715606/Dockerfile.txt)

**Comment by madhuakula** [comment]
Hey @phpsystems 

Yes, you are right. Thanks a ton for submitting all the details 🙏 

It was added at #46 the same issue with Golang binaries being AMD64, please feel free to make a PR if you have any fixes. I didn't get time to fix Dockerfiles and builds yet. Hopefully, I can fix this by tonight or tomorrow otherwise.

Thanks a mil once again!

**Comment by phpsystems** [comment]
Now it is my turn to do as you command :-)

**Comment by madhuakula** [comment]
Thanks to both (@phpsystems and @adamhurm) of you, I hope these bugs are fixed in #48. Please do let me know if you still face any issues 🙏
