### ISSUE TITLE
Kubernetes Goat communication community setup

### ISSUE THREAD

**Issue by madhuakula** [madhuakula/kubernetes-goat#50]
Kubernetes Goat 🐐 has grown significantly beyond expectations. Also, the vision and the future are so huge that I wanted to take this to the next level. 

So we are going to build a community around it, which helps to grow this project and help to learn and share the Kubernetes and Cloud Native security with everyone.

We are going to create a discord server for the Kubernetes goat soon 🚀

**Comment by 0xCardinal** [comment]
Hey @madhuakula, I am working on it. Will update as soon as it is complete.

**Comment by madhuakula** [comment]
Looks like something is cooking 🤖  🚀  🔥 

Cool stuff @0xCardinal 👏 

![kubernetes-goat-discord-sneak](https://user-images.githubusercontent.com/6764192/169159980-69735fca-0fe8-4066-8a82-6e1f24c06844.png)

**Comment by 0xCardinal** [comment]
Hey!

Discord Server is now ready - [rebrand.ly/Kubernetes-Goat](https://rebrand.ly/Kubernetes-Goat)

![image](https://user-images.githubusercontent.com/77858203/169398094-c5c9d691-7a11-46c6-aa41-4bf1dcc39d60.png)

**Comment by madhuakula** [comment]
Thanks a million, @0xCardinal for helping with setting up the Discord server #53

Let's build an awesome community folks 🥳
