### ISSUE TITLE
Bug: No reaction on web interface

### ISSUE THREAD

**Issue by wurstbrot** [madhuakula/kubernetes-goat#6]
When I click on one of the menu items, nothing happens.
Expected is that the content in the main view changes.

Deployment: minikube
![image](https://user-images.githubusercontent.com/955192/84800323-ef06ac00-affd-11ea-84ba-22ba3fa94b84.png)

The js debuger show no errors (except favicon missing)

**Comment by madhuakula** [comment]
Oh sorry, that's my bad. It's a different image. Just pushed https://github.com/madhuakula/kubernetes-goat/commit/9b6cf784a75bde39509a2ddac1206828d2d818d2

Could you please update the `scenarios/kubernetes-goat-home/deployment.yaml` from the latest changes. 

Thanks
