### ISSUE TITLE
"⎈ Container escape to the host system"cannot access port 1233

### ISSUE THREAD

**Issue by Is4b3lla3** [madhuakula/kubernetes-goat#69]
with m1 mac
<img width="842" alt="image" src="https://user-images.githubusercontent.com/37106292/188373109-f780b96e-5de6-485d-af70-8e1f9e1647ff.png">

**Comment by josephwhenry** [comment]
Looks similar to #66

**Comment by Is4b3lla3** [comment]
> Looks similar to #66

yes，All because the container "monitor" crashed
