### ISSUE TITLE
DIND (docker-in-docker) scenario missing tar binary, unable to complete scenario

### ISSUE THREAD

**Issue by mrintern** [madhuakula/kubernetes-goat#80]
@madhuakula 
In scenario 2, DIND, `tar` is required to unzip the docker binary we download from the internet using wget. `/usr/bin/tar` is missing, preventing one from completing the scenario.

I actually tried grabbing tar from my local machine using wget to complete the scenario but I wasn't able to get it to work, and it's difficult to understand whats wrong without a shell  (all i see from the ping service is exit codes)

Am I missing something? Seems to me like the scenario is broken. I ran through the first scenario without issues.

My setup:
- windows subsystem for linux 2 (WSL2) (ubuntu app)
- Windows 11 underneath that
- deployed K8S goat using KinD

**Comment by madhuakula** [comment]
Hi @mrintern 

Thanks for reporting this. Unfortunately I don't have the WSL setup to test. But looking at its mostly issue with the binaries and the environment you are running, let me revamp the scenario execution environment to work seamlessly for everyone regardless of environment.

Hopefully I will try to make a fix by this weekend.

**Comment by madhuakula** [comment]
I think you can leverage the static binaries in the pod https://download.docker.com/linux/static/stable/. Not sure if this helps in the WSL setup, I would also recommend checking two things

1. Container runtime
2. Support the downloaded container binary (docker, ctr, etc.) so you can interact with the respective socket.

**Comment by nmiekley** [comment]
I didn't see https://github.com/madhuakula/kubernetes-goat/issues/95 earlier, but it could be fixed by this. However, I only have tested this in kind and AWS yet.

**Comment by madhuakula** [comment]
It should be fixed with the recent fix from #150
