### ISSUE TITLE
Metadata-db pod isn't installed by setup-kubernetes-goat.sh

### ISSUE THREAD

**Issue by cadgo** [madhuakula/kubernetes-goat#86]
Environment

OS: Kali Linux Rolling
K8s: K3D
Docker: Client: Docker Engine - Community
 Version:           20.10.21
 API version:       1.41
Helm: v2.17.0

Deploying the environment using helm drops the next error.

kubectl setup looks good.                                                                                                                            [40/745]
deploying insecure super admin scenario
serviceaccount/superadmin created
clusterrolebinding.rbac.authorization.k8s.io/superadmin created
deploying helm chart metadata-db scenario
Error: This command needs 1 argument: chart name <-- Error for a chart name
deploying the vulnerable scenarios manifests
job.batch/batch-check-job created
deployment.apps/build-code-deployment created
service/build-code-service created                                                                                                                           namespace/secure-middleware created
service/cache-store-service created
deployment.apps/cache-store-deployment created
deployment.apps/health-check-deployment created
service/health-check-service created
namespace/big-monolith created
role.rbac.authorization.k8s.io/secret-reader created
rolebinding.rbac.authorization.k8s.io/secret-reader-binding created
serviceaccount/big-monolith-sa created
secret/vaultapikey created
secret/webhookapikey created
deployment.apps/hunger-check-deployment created
service/hunger-check-service created
deployment.apps/internal-proxy-deployment created
service/internal-proxy-api-service created
service/internal-proxy-info-app-service created
deployment.apps/kubernetes-goat-home-deployment created
service/kubernetes-goat-home-service created
deployment.apps/poor-registry-deployment created
service/poor-registry-service created
secret/goatvault created
deployment.apps/system-monitor-deployment created
service/system-monitor-service created
job.batch/hidden-in-layers created
Successfully deployed Kubernetes Goat. Have fun learning Kubernetes Security!
Ensure pods are in running status before running access-kubernetes-goat.sh script
Now run the bash access-kubernetes-goat.sh to access the Kubernetes Goat environment.

kubectl get pods -A
NAMESPACE           NAME                                               READY   STATUS              RESTARTS      AGE
kube-system         coredns-b96499967-jbh9c                            1/1     Running             0             13m
kube-system         local-path-provisioner-7b7dc8d6f5-hw5fj            1/1     Running             0             13m
kube-system         helm-install-traefik-crd-2gl6r                     0/1     Completed           0             13m
kube-system         svclb-traefik-7bcd6545-nnpkj                       2/2     Running             0             13m
kube-system         helm-install-traefik-69587                         0/1     Completed           1             13m
kube-system         metrics-server-668d979685-b4pk2                    1/1     Running             0             13m
kube-system         traefik-7cd4fcff68-6gvmh                           1/1     Running             0             13m
kube-system         tiller-deploy-77db84774f-49r6j                     1/1     Running             0             8m44s
default             health-check-deployment-f9d6f6f9c-v7tct            0/1     ContainerCreating   0             8m24s
default             batch-check-job-lvxfh                              0/1     Completed           0             8m25s
default             hidden-in-layers-nc4ph                             1/1     Running             0             8m21s
secure-middleware   cache-store-deployment-754d469fdc-5q5cp            1/1     Running             0             8m24s
default             kubernetes-goat-home-deployment-866d467dfd-24kd8   1/1     Running             0             8m23s
big-monolith        hunger-check-deployment-cc7758676-7bntj            1/1     Running             0             8m23s
default             poor-registry-deployment-5dbb7ccddb-gdwq7          1/1     Running             0             8m22s
default             build-code-deployment-64f9dc8b78-wbtwd             1/1     Running             0             8m25s
default             system-monitor-deployment-69477d6d49-7xn9g         1/1     Running             0             8m22s
default             internal-proxy-deployment-567dc6dcb5-74kqv         1/2     CrashLoopBackOff    5 (52s ago)   8m23s

metdata-db pod is not deployed

**Comment by madhuakula** [comment]
@cadgo thanks for reporting the issue. Looks like it had issue with other folks as well, mostly the issue was the resources as per testing. Fixing and releasing the update today 🚀

**Comment by madhuakula** [comment]
@suneshgovind could you please help with this fix for resource limits?

Thank you so much

**Comment by madhuakula** [comment]
Here is the resource limits setup https://github.com/madhuakula/kubernetes-goat/blob/master/scenarios/metadata-db/values.yaml#L37-L42

**Comment by madhuakula** [comment]
Fixed the issue. Thank you so much @cadgo for reporting :pray:
