### ISSUE TITLE
Few issues

### ISSUE THREAD

**Issue by c0ldb00t3r** [madhuakula/kubernetes-goat#9]
1. in setting up google cluster
_export KUBERNETESGOATPROJECTNAME="YOUR GOOGLE PROJECT NAME"_
Project name & project id both are different.
gcloud --project only supports project id not name.

2. After running access-kubernetes-goat.sh. some of the containers still not forwarding ports.  seems like need few sleep :)
![image](https://user-images.githubusercontent.com/10518727/85014988-d96fbe80-b184-11ea-82d4-7666805d5c30.png)

**Comment by madhuakula** [comment]
Thanks @c0ldb00t3r for the feedback, I will update these things in documentation fix in scripts as well to give more sleep.

**Comment by myugan** [comment]
@c0ldb00t3r did you try to forward the port using this tools https://github.com/txn2/kubefwd?

**Comment by madhuakula** [comment]
Pushed the changes for fix. Closing this task

@myugan yes you can use that tool. But the idea here is to use default built-in kubectl features rather installing another tool as pre requisite. But thanks for the suggestion, keep them coming 👍 

Thanks again!
