### ISSUE TITLE
health-check-deployment-77c7b6686-dwb6s not starting on Kind

### ISSUE THREAD

**Issue by pranabtandon** [madhuakula/kubernetes-goat#95]
I am trying to create kubernetes-goat on kind on Linux Ubuntu VM. This particular POD is not getting started (health-check-deployment-77c7b6686-dwb6s)

ptandon@ptandon-VirtualBox:~/kubernetes-goat$ sudo kubectl get pods
NAME                                               READY   STATUS              RESTARTS   AGE
batch-check-job-p4jjp                              0/1     Completed           0          28m
build-code-deployment-57974868c5-knmrq             1/1     Running             0          28m
health-check-deployment-77c7b6686-dwb6s            0/1     ContainerCreating   0          28m
hidden-in-layers-f6hds                             1/1     Running             0          28m
internal-proxy-deployment-598c9c6666-65qxz         2/2     Running             0          28m
kubernetes-goat-home-deployment-74cd49bf79-d9qx2   1/1     Running             0          28m
metadata-db-86579bcb65-29cmq                       1/1     Running             0          28m
poor-registry-deployment-cc975f599-pgxqm           1/1     Running             0          28m
system-monitor-deployment-756598dbd-fwzzv          1/1     Running             0          28m

When I try to debug this further using # kubectl describe health-check-deployment-77c7b6686-dwb6s

Events:
  Type     Reason       Age                  From               Message
  ----     ------       ----                 ----               -------
  Normal   Scheduled    35m                  default-scheduler  Successfully assigned default/health-check-deployment-77c7b6686-dwb6s to kind-control-plane
  Warning  FailedMount  10m (x5 over 28m)    kubelet            Unable to attach or mount volumes: unmounted volumes=[docker-sock-volume], unattached volumes=[kube-api-access-cf69j docker-sock-volume]: timed out waiting for the condition
  Warning  FailedMount  6m16s (x5 over 33m)  kubelet            Unable to attach or mount volumes: unmounted volumes=[docker-sock-volume], unattached volumes=[docker-sock-volume kube-api-access-cf69j]: timed out waiting for the condition
  Warning  FailedMount  2m8s (x21 over 35m)  kubelet            MountVolume.SetUp failed for volume "docker-sock-volume" : hostPath type check failed: /var/run/docker.sock is not a socket file

**Comment by pranabtandon** [comment]
Update: This has been fixed. I was using conatinerD as containerruntime so I changed it scenarios/health-check/deployment.yaml

volumes:
        - name: docker-sock-volume
          hostPath:
            path: /var/run/containerd/containerd.sock
            type: Socket

**Comment by jrknox1977** [comment]
I have had to look this up and fix a few times. For now I am creating a fork and fixing it for my automation. 
Kubeadm uses containerd, should there be a kubeadm version of this file? Just like there is a kind version?

**Comment by madhuakula** [comment]
Interesting, I think it's due to the underlying container runtime. I think we can have a simple fix based on the runtime to pass the socket or even I can make it in such a way it supports both. I will fix this soon this week after my KubeCon talk https://sched.co/1HyQj

**Comment by pr0b3r7** [comment]
Hi @madhuakula congrats on the talk @ KubeCon... -- Is this issue related to :1231 not responding by any chance? Did you get a moment to take a look at a potential fix? My team and I area experiencing something similar... 
<img width="783" alt="image" src="https://github.com/madhuakula/kubernetes-goat/assets/14915771/e37a84ea-8514-4e36-8ca5-9d0319dbca18">

**Comment by madhuakula** [comment]
Apologies for the delays. I think the updated container is not pushed to upstream, also I was away for a while and working on this now.

**Comment by nmiekley** [comment]
This would probably solve this: https://github.com/madhuakula/kubernetes-goat/discussions/127

**Comment by madhuakula** [comment]
I think this should fix this #150
