### ISSUE TITLE
Container escape to the host system non functionnal

### ISSUE THREAD

**Issue by zepouet** [madhuakula/kubernetes-goat#97]
Hello,

I am trying to do the workshop on KIND and on other Cloud Provider. Always the same issue with this workshop about container escape.

Instead of 
![image](https://user-images.githubusercontent.com/231269/229812132-4bda161c-56f3-4a24-ac45-db4316f0bf4e.png)

We are directly on the host 
<img width="634" alt="Capture d’écran 2023-04-04 à 15 44 10" src="https://user-images.githubusercontent.com/231269/229812410-cc178dec-3518-4348-bcd6-2c7d6086378f.png">

So no way to use it.
Thanks a lot for your work

Best regards,

**Comment by zepouet** [comment]
Thanks a lot @madhuakula 
The issue is on all platform.

Best regards,

**Comment by madhuakula** [comment]
Hmm, interesting. I tested with GKE, DO, etc. It works fine, I see only this in KIND. Can you provide which platforms you see the same issue with?

Thank you!

**Comment by madhuakula** [comment]
This has been fixed @zepouet at https://github.com/madhuakula/kubernetes-goat/commit/d385a5284c52cada8767c604eabf0425f8f7efa6
<img width="961" alt="Screenshot 2023-04-08 at 11 36 49" src="https://user-images.githubusercontent.com/6764192/230714524-d3e0ac7e-69fc-4413-abe0-7db7293ea3c6.png">

**Comment by theoberthier** [comment]
Hi, I have a same issue with helm & minikube configuration.

**Comment by chayuto** [comment]
also have the same issue with AWS setup 

![Image](https://github.com/user-attachments/assets/5650bba1-dbd9-4bdf-a846-7fa142f25e2a)
